export const DataDisposeTitle = [
	{ name: "上报时间", value: "UpTime", field: 'UpTime' },
	{ name: "上报类型", value: "EventFromName", field: 'EventFromName' },
	{ name: "事件编号", value: "EventCode", width: 100, field: 'EventCode' },
	{ name: "处理时间", value: "ExecTime", field: 'ExecTime' },
	{ name: "紧急状态", value: "UrgencyId", field: 'UrgencyId' },
	{ name: "事件状态", value: "OperId", field: 'OperId' },
	{
		name: "事件类型", value: "EventTypeName", field: '8', templet: function (row) {
			return `<span class="el-tag">${row.EventTypeName}</span>`
		}
	},
	{ name: "事件内容", value: "EventTypeName2", field: 'EventTypeName2' },
	{ name: "上报人", value: "PersonName", field: 'PersonName' },
	{ name: "步骤处理人", value: "ExecPersonName", field: 'ExecPersonName' },
	{ name: "处理单位", value: "ExecDetpName", field: 'ExecDetpName' },
	{ name: "联系人", value: "LinkMan", field: 'LinkMan' },
	{ name: "联系电话", value: "LinkCall", width: 96, field: 'LinkCall' },
	{ name: "更新时间", value: "EventUpdateTime", field: 'EventUpdateTime' }
]
const evevtTypeFilter = {
	1: 'abc',
	2: 'hahah'
}

export const DataDispose = [
	{
		"EventCode": "DH190001406",
		"EventAddress": "1",
		"UpTime": "2019-07-24T17:46:10",
		"DeptId": 1, "PersonId": 1,
		"PersonName": "admin",
		"cDepName": "管理层",
		"cRoleName": "设备科",
		"EventTypeId": 1,
		"EventTypeId2": 1,
		"EventTypeName": "困难用水",
		"EventTypeName2": "困难用水",
		"EventFromId": 3,
		"EventFromName": "巡检上报",
		"UrgencyId": 1,
		"UrgencyName": "一般",
		"DispatchPerson": null,
		"DispatchPersonName": null,
		"EventPictures": "/upload/EventsImg/2019/7/24/2019072417461024.png|/upload/EventsImg/2019/7/24/2019072417461087.png|",
		"EventDesc": "1",
		"EventX": "1",
		"EventY": "1",
		"EventUpdateTime": "2019-07-24T17:46:10",
		"IsValid": 1,
		"IsValidName": "正常",
		"Devicesmid": null,
		"DevicesType": null,
		"DeleteStatus": "0",
		"TaskId": -1,
		"Remark_Back": null,
		"OtherSysEventId": null,
		"ExecTime": 36,
		"OperId": null,
		"OperName": null,
		"OrderId": null,
		"IsFinish": 0,
		"LinkMan": "1",
		"LinkCall": "1",
		"EventStatus": 4,
		"StatusName": "正常",
		"ExecPersonId": null,
		"ExecUpDateTime": null,
		"ExecDetpID": null,
		"ExecDetpName": null,
		"ExecPersonName": null,
		"DispatchPersonID": null,
		"DispatchPersonName2": null,
		"DispatchPersonDeptName": null,
		"OperName2": null,
		"OperRemarks": null,
		"DispatchPersonTelePhone": null,
		"LeakPipeCaliber": null,
		"LeakType": null,
		"Pos": 1
	},
	{
		"EventCode": "DH190001406",
		"EventAddress": "1",
		"UpTime": "2019-07-24T17:46:10",
		"DeptId": 1, "PersonId": 1,
		"PersonName": "admin",
		"cDepName": "管理层",
		"cRoleName": "设备科",
		"EventTypeId": 1,
		"EventTypeId2": 1,
		"EventTypeName": "困难用水",
		"EventTypeName2": "困难用水",
		"EventFromId": 3,
		"EventFromName": "巡检上报",
		"UrgencyId": 1,
		"UrgencyName": "一般",
		"DispatchPerson": null,
		"DispatchPersonName": null,
		"EventPictures": "/upload/EventsImg/2019/7/24/2019072417461024.png|/upload/EventsImg/2019/7/24/2019072417461087.png|",
		"EventDesc": "1",
		"EventX": "1",
		"EventY": "1",
		"EventUpdateTime": "2019-07-24T17:46:10",
		"IsValid": 1,
		"IsValidName": "正常",
		"Devicesmid": null,
		"DevicesType": null,
		"DeleteStatus": "0",
		"TaskId": -1,
		"Remark_Back": null,
		"OtherSysEventId": null,
		"ExecTime": 36,
		"OperId": null,
		"OperName": null,
		"OrderId": null,
		"IsFinish": 0,
		"LinkMan": "1",
		"LinkCall": "1",
		"EventStatus": 2
	},
	{
		"EventCode": "DH190001406",
		"EventAddress": "1",
		"UpTime": "2019-07-24T17:46:10",
		"DeptId": 1, "PersonId": 1,
		"PersonName": "admin",
		"cDepName": "管理层",
		"cRoleName": "设备科",
		"EventTypeId": 1,
		"EventTypeId2": 1,
		"EventTypeName": "困难用水",
		"EventTypeName2": "困难用水",
		"EventFromId": 3,
		"EventFromName": "巡检上报",
		"UrgencyId": 1,
		"UrgencyName": "一般",
		"DispatchPerson": null,
		"DispatchPersonName": null,
		"EventPictures": "/upload/EventsImg/2019/7/24/2019072417461024.png|/upload/EventsImg/2019/7/24/2019072417461087.png|",
		"EventDesc": "1",
		"EventX": "1",
		"EventY": "1",
		"EventUpdateTime": "2019-07-24T17:46:10",
		"IsValid": 1,
		"IsValidName": "正常",
		"Devicesmid": null,
		"DevicesType": null,
		"DeleteStatus": "0",
		"TaskId": -1,
		"Remark_Back": null,
		"OtherSysEventId": null,
		"ExecTime": 36,
		"OperId": null,
		"OperName": null,
		"OrderId": null,
		"IsFinish": 0,
		"LinkMan": "1",
		"LinkCall": "1",
		"EventStatus": 6
	},
	{
		"EventCode": "DH190001406",
		"EventAddress": "1",
		"UpTime": "2019-07-24T17:46:10",
		"DeptId": 1, "PersonId": 1,
		"PersonName": "admin",
		"cDepName": "管理层",
		"cRoleName": "设备科",
		"EventTypeId": 1,
		"EventTypeId2": 1,
		"EventTypeName": "困难用水",
		"EventTypeName2": "困难用水",
		"EventFromId": 3,
		"EventFromName": "巡检上报",
		"UrgencyId": 1,
		"UrgencyName": "一般",
		"DispatchPerson": null,
		"DispatchPersonName": null,
		"EventPictures": "/upload/EventsImg/2019/7/24/2019072417461024.png|/upload/EventsImg/2019/7/24/2019072417461087.png|",
		"EventDesc": "1",
		"EventX": "1",
		"EventY": "1",
		"EventUpdateTime": "2019-07-24T17:46:10",
		"IsValid": 1,
		"IsValidName": "正常",
		"Devicesmid": null,
		"DevicesType": null,
		"DeleteStatus": "0",
		"TaskId": -1,
		"Remark_Back": null,
		"OtherSysEventId": null,
		"ExecTime": 36,
		"OperId": null,
		"OperName": null,
		"OrderId": null,
		"IsFinish": 0,
		"LinkMan": "1",
		"LinkCall": "1",
		"EventStatus": 3
	},
	{
		"EventCode": "DH190001406",
		"EventAddress": "1",
		"UpTime": "2019-07-24T17:46:10",
		"DeptId": 1, "PersonId": 1,
		"PersonName": "admin",
		"cDepName": "管理层",
		"cRoleName": "设备科",
		"EventTypeId": 1,
		"EventTypeId2": 1,
		"EventTypeName": "困难用水",
		"EventTypeName2": "困难用水",
		"EventFromId": 3,
		"EventFromName": "巡检上报",
		"UrgencyId": 1,
		"UrgencyName": "一般",
		"DispatchPerson": null,
		"DispatchPersonName": null,
		"EventPictures": "/upload/EventsImg/2019/7/24/2019072417461024.png|/upload/EventsImg/2019/7/24/2019072417461087.png|",
		"EventDesc": "1",
		"EventX": "1",
		"EventY": "1",
		"EventUpdateTime": "2019-07-24T17:46:10",
		"IsValid": 1,
		"IsValidName": "正常",
		"Devicesmid": null,
		"DevicesType": null,
		"DeleteStatus": "0",
		"TaskId": -1,
		"Remark_Back": null,
		"OtherSysEventId": null,
		"ExecTime": 36,
		"OperId": null,
		"OperName": null,
		"OrderId": null,
		"IsFinish": 0,
		"LinkMan": "1",
		"LinkCall": "1",
		"EventStatus": 5
	}
]
